Desktop/group_e-main/conf/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('uploader.urls')),
]


# 開発環境でのメディアファイルの配信設定
urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

Desktop/group_e-main/uploader/urls.py
from django.urls import path
from . import views

app_name = 'uploader'

urlpatterns = [
    path('', views.ImageListView.as_view(), name='image_list'),
    path('image/create/', views.ImageCreateView.as_view(), name='image_create'),
]

Desktop/group_e-main/uploader/models.py
from django.db import models


class Image(models.Model):
    title = models.CharField('タイトル', max_length=255)
    file = models.ImageField('ファイル')

    def __str__(self):
        return self.title

Desktop/group_e-main/uploader/forms.py
from django import forms
from .models import Image


class ImageCreateForm(forms.ModelForm):

    class Meta:
        model = Image
        fields = ('title', 'file')

Desktop/group_e-main/uploader/views.py
from django.views import generic
from django.urls import reverse_lazy
from .models import Image
from .forms import ImageCreateForm


class ImageListView(generic.ListView):
    model = Image
    template_name = 'uploader/image_list.html'


class ImageCreateView(generic.CreateView):
    model = Image
    form_class = ImageCreateForm
    template_name = 'uploader/image_create.html'
    success_url = reverse_lazy('uploader:image_list')

Desktop/group_e-main/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

<nav id="menu">
    <div class="container">
      <ul>
        <li><a href="{% url 'uploader:image_list' %}">画像一覧</a></li>
        <li><a href="{% url 'uploader:image_create' %}">画像作成</a></li>
      </ul>
    </div>
</nav>

<div class="container">
    {% block content %}
    {% endblock %}
</div>

</body>
</html>

Desktop/group_e-main/templates/uploader/image_create.html
{% extends 'base.html' %}

{% block content %}
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_div }}
        <button type="submit">送信</button>
    </form>
{% endblock %}

Desktop/group_e-main/templates/uploader/image_list.html
{% extends 'base.html' %}

{% block content %}
<div class="image-list">
    {% for image in image_list %}
        <div>
            <p>{{ image.title }}</p>
            <img src="{{ image.file.url }}">
        </div>
    {% endfor %}
</div>

{% endblock %}